// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type MigrationBaseline struct {
	ID          pgtype.UUID `json:"id"`
	CreatedAt   time.Time   `json:"created_at"`
	Description string      `json:"description"`
}
