// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateMigrationBaseline(ctx context.Context, description string) (MigrationBaseline, error)
	GetMigrationBaseline(ctx context.Context, id pgtype.UUID) (MigrationBaseline, error)
	ListMigrationBaselines(ctx context.Context) ([]MigrationBaseline, error)
}

var _ Querier = (*Queries)(nil)
